require("barbecue").setup({
	  symbols = {
		modified = "●",
		ellipsis = "…",
		separator = "",
	},
	kinds = {
		File = " ",
		Package = "",
		Module = "",
		Namespace = "",
		Macro = "ﰠ",
		Class = "ﴯ",
		Constructor = "",
		Field = "ﰠ",
		Property = "ﰠ",
		Method = "",
		Struct = "פּ",
		Event = "",
		Interface = "",
		Enum = "",
		EnumMember = "",
		Constant = "",
		Function = "",
		TypeParameter = "",
		Variable = "",
		Operator = "",
		Null = "",
		Boolean = "01",
		Number = "",
		String = "",
		Key = "",
		Array = "",
		Object = "ﰠ",
	},
})
