require('plugins')

require('autocmd')
require('settings')
require('keys')

require('colors')
require('eviline')
-- require('statusline')
require('buffer')
require('nvtree')
require('treesitter')
require('dashboard')
require('indent')
require('tel')
require('pairs')
require('saga')
require('scroll')
require('lsptrouble')
require('term')
require('git')
require('icons')
require('diaal')
-- require('discord')
require('motion')
require('which')
-- require('zen')

require('rg-source')
require('lsp-compe')
require('lsp-kind')
require('lsp')
