return {
	"nvim-telescope/telescope.nvim",
	cmd = "Telescope",
	dependencies = {
		{ "nvim-lua/plenary.nvim" },
	},
	keys = {
		{ "<leader>ff", "<cmd>Telescope find_files<CR>", desc = "Find Files" },
		{ "<leader>fw", "<cmd>Telescope live_grep<CR>", desc = "Find a string" },
		{ "<leader>fb", "<cmd>Telescope buffers<CR>", desc = "Find buffers" },
		{ "<leader>fr", "<cmd>Telescope oldfiles<CR>", desc = "Find recent file" },
		{ "<leader>fk", "<cmd>Telescope keymaps<CR>", desc = "Find keymaps" },
		{ "<leader>fc", "<cmd>Telescope find_files cwd=$HOME/.config/nvim/<CR>", desc = "Open config" },
	},
	config = function ()

		require("telescope").setup({
			defaults = {
				find_command = { "rg", "--no-heading", "--with-filename", "--line-number", "--column", "--smart-case" },
				prompt_prefix = "   ",
				entry_prefix = "  ",
				initial_mode = "insert",
				selection_caret = "    ",
				path_display = { "smart" },
				selection_strategy = "reset",
				sorting_strategy = "descending",
				layout_strategy = "horizontal",
				winblend = 0,
				layout_config = {
					horizontal = {
						prompt_position = "bottom",
						preview_width = 0.55,
						results_width = 0.8,
					},
					vertical = {
						mirror = false,
					},
					width = 0.85,
					height = 0.80,
					preview_cutoff = 120,
				},
				-- border = {},
				-- borderchars = { "█", " ", "▀", "█", "█", " ", " ", "▀" },
				-- borderchars = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
				borderchars = {
					prompt = { "─", " ", " ", " ", "─", "─", " ", " " },
					results = { " " },
					preview = { " " },
				},
				color_devicons = true,
				use_less = true,
				set_env = { ["COLORTERM"] = "truecolor" },

				file_ignore_patterns = {
					"phaser.min.js",
					"phaser.d.ts",
					".git/",
					"target/",
					"docs/",
					"vendor/*",
					"%.lock",
					"__pycache__/*",
					"%.sqlite3",
					"%.ipynb",
					"node_modules/*",
					-- "%.jpg",
					-- "%.jpeg",
					-- "%.png",
					"%.svg",
					"%.otf",
					"%.ttf",
					"%.webp",
					".dart_tool/",
					".github/",
					".gradle/",
					".idea/",
					".settings/",
					".vscode/",
					"__pycache__/",
					"build/",
					"gradle/",
					"node_modules/",
					"%.pdb",
					"%.dll",
					"%.class",
					"%.exe",
					"%.cache",
					"%.ico",
					"%.pdf",
					"%.dylib",
					"%.jar",
					"%.docx",
					"%.met",
					"smalljre_*/*",
					".vale/",
					"%.burp",
					"%.mp4",
					"%.mkv",
					"%.rar",
					"%.zip",
					"%.7z",
					"%.tar",
					"%.bz2",
					"%.epub",
					"%.flac",
					"%.tar.gz",
				},
				mappings = {
					i = {
						["<C-j>"] = require("telescope.actions").move_selection_next,
						["<C-k>"] = require("telescope.actions").move_selection_previous,
						["<esc>"] = require("telescope.actions").close,
					},

					n = {
						["<C-j>"] = require("telescope.actions").move_selection_next,
						["<C-k>"] = require("telescope.actions").move_selection_previous,
					},
				},
			},
		})
	end,
}
